# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Initialize git
        shell: powershell
        run: git config --global core.autocrlf false
      - uses: actions/checkout@v2
      - name: Setup Perl
        uses: shogo82148/actions-setup-perl@v1.8.3
        with:
          distribution: strawberry
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Setup MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
            platform: x86
            cygwin: 1
            static: 1
            cc: 1
      - name: Bootstrap
        shell: powershell
        run: python ./cerbero-uninstalled -c config/win32.cbc -v visualstudio bootstrap
        env:
          PATH: C:\tools\mingw64\bin;C:\tools\mingw64\msys\1.0\bin;${env:PATH}

      # Runs a set of commands using the runners shell
      - name: Build
        run: python ./cerbero-uninstalled -c config/win32.cbc -v visualstudio package gstreamer-1.0
        env:
          PATH: C:\tools\mingw64\bin;C:\tools\mingw64\msys\1.0\bin;${env:PATH}
